tracker/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/',  views.register, name='register'),
    url(r'^login/',  views.login_, name='login'),
    url(r'^logout/', views.logout_, name='logout'),
    url(r'^home/',  views.home, name='home'),
]

trackmyrun/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url('', include('tracker.urls', namespace="tracker")),
    url(r'^api/', include('tracker.rest_urls', namespace="api")),
]

tracker/models.py
from django.contrib.gis.db import models
from django.contrib.gis.geos.collections import LineString
from django.contrib.auth.models import User


class Activity(models.Model):
    id = models.AutoField(primary_key=True)
    start = models.DateTimeField()
    end = models.DateTimeField()
    owner = models.ForeignKey(
        User,
        verbose_name="owner",
        on_delete=models.CASCADE,
        default=1
    )
    activity_type = models.CharField(
        max_length=100,
        verbose_name="activity_type"
    )
    created = models.DateTimeField(
        auto_now_add=True
    )
    route = models.LineStringField(verbose_name="route",
                                   default=LineString)
    distance = models.FloatField(verbose_name="length", default=0)

tracker/forms.py
from django import forms


class PasswordForm(forms.Form):
    password = forms.CharField(
        max_length=128,
        widget=forms.PasswordInput(),
        label="Enter password"
    )
    password2 = forms.CharField(
        max_length=128,
        widget=forms.PasswordInput(),
        label="Re-enter password"
    )

    def clean_password2(self):
        password = self.cleaned_data.get('password', '')
        password2 = self.cleaned_data['password2']
        if password != password2:
            raise forms.ValidationError("Confirmation password doesn't match.")
        return password2


# form for registration
class RegisterForm(PasswordForm):
    first_name = forms.CharField(
        label="Firstname",
        max_length=50,
        required=True,
    )
    last_name = forms.CharField(
        label="Lastname",
        max_length=50,
        required=True,
    )
    email = forms.EmailField(
        label="Email",
        max_length=255,
        required=True,
    )
    username = forms.CharField(
        label="Username",
        max_length=255,
        required=True,
    )


# form for logging in
class LoginForm(forms.Form):
    password = forms.CharField(
        label="Password",
        max_length=128,
        widget=forms.PasswordInput(),
        required=True
    )
    username = forms.CharField(
        label="Username",
        max_length=255,
        required=True,
    )

tracker/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.forms import ValidationError
from . import forms


def index(request):
    if request.user.is_authenticated():
        return redirect(reverse('tracker:home'))
    else:
        return redirect(reverse('tracker:login'))


def register(request):
    if request.POST:
        form = forms.RegisterForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            password = form.cleaned_data['password']

            try:
                user = get_user_model().objects.get(username=username)
                if user:
                    form.add_error(None, ValidationError('This user already exists.'))
            except get_user_model().DoesNotExist:
                user = get_user_model().objects.create_user(username=username)
                user.set_password(password)
                user.email = email
                user.first_name = first_name
                user.last_name = last_name
                user.save()
                return redirect(reverse('tracker:login'))

    else:
        form = forms.RegisterForm()
    return render(request, 'tracker/register.html', {'form': form})


def login_(request):
    if request.POST:
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    login(request, user)
                    return redirect(reverse('tracker:home'))
                else:
                    form.add_error(None, ValidationError(
                        "Your account is not active."
                    ))
            else:
                form.add_error(None, ValidationError(
                    "Incorrect email or password"
                ))
    else:
        form = forms.LoginForm()
    return render(request, 'tracker/login.html', {'form': form})


@login_required
def logout_(request):
    logout(request)
    return redirect(reverse('tracker:login'))


@login_required
def home(request):
    return render(request, 'tracker/home.html')

templates/tracker/base.html
<html xmlns="http://www.w3.org/1999/html">
{% load staticfiles %}
{% load leaflet_tags %}
<head>

    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
          integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ"
          crossorigin="anonymous">
    <script
            src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>
    <script
            src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"
            integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
            integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment-with-locales.js"></script>
    <script src="{% static 'tracker/js/activityRenderer.js' %}"></script>

</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

templates/tracker/home.html
{% extends "tracker/base.html" %}
{% load staticfiles %}
{% load leaflet_tags %}
{% block content %}
    <head>

        {% leaflet_css plugins="forms" %}
        {% leaflet_js plugins="forms" %}

        <title>Track My Run | Home</title>
    </head>
    <body>
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'tracker:home' %}">Track My Run | Home</a>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link" href="{% url 'tracker:logout' %}">Logout</a>
            </div>
        </div>
    </nav>

    {% leaflet_map "map" callback="initMap" %}
    <div style="width: 80%; margin-left: 10%; margin-top: 20px;">
        <h3>Activities</h3>
        <div id="activities"></div>
    </div>
    </body>

    <script type="text/javascript">
        // Load activities.
        var globalMap = null;
        $(document).ready(function () {
            var featureCollection = null;
            $.get({
                url: '/api/activity',
                success: function (data) {
                    featureCollection = data;
                    actvityRenderer('#activities').displayInTable(featureCollection.features, handleActivityClick);
                }
            });

            function handleActivityClick(index) {
                var activity = featureCollection.features[index];
                actvityRenderer().displayOnMap(globalMap, activity);
            }
        });
        function initMap(map) {
            globalMap = map;
        }
    </script>
{% endblock %}

templates/tracker/login.html
{% extends "tracker/base.html" %}
{% load staticfiles %}

{% block content %}
    <head>
        <title>Track My Run | Login</title>
    </head>
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand">Track My Run | Home</a>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link" href="{% url 'tracker:register' %}">Register</a>
            </div>
        </div>
    </nav>
    {# any login errors#}
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger" role="alert">
                    <strong>Woops!</strong> {{ error|escape }}
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                <strong>Woops!</strong> {{ error|escape }}
            </div>
        {% endfor %}
    {% endif %}

    <div class="container">
        <form method="post" action="{% url 'tracker:login' %}">
            {% csrf_token %}
            <table>
                <tr>
                    <td>{{ form.username.label_tag }}</td>
                    <td>{{ form.username }}</td>
                </tr>
                <tr>
                    <td>{{ form.password.label_tag }}</td>
                    <td>{{ form.password }}</td>
                </tr>

            </table>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

templates/tracker/register.html
{% extends "tracker/base.html" %}
{% load staticfiles %}

{% block content %}
    <head>
        <title>Track My Run | Register</title>
    </head>
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand">Track My Run | Home</a>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link" href="{% url 'tracker:login' %}">Login</a>
            </div>
        </div>
    </nav>
    {# any registration errors#}
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger" role="alert">
                    <strong>Woops!</strong> {{ error|escape }}
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                <strong>Woops!</strong> {{ error|escape }}
            </div>
        {% endfor %}
    {% endif %}

    <div class="register-area container">
        <form method="post" action="{% url 'tracker:register' %}">
            {% csrf_token %}
            <table>
                <tr>
                    <td>{{ form.first_name.label_tag }}</td>
                    <td>{{ form.first_name }}</td>
                </tr>
                <tr>
                    <td>{{ form.last_name.label_tag }}</td>
                    <td>{{ form.last_name }}</td>
                </tr>
                <tr>
                    <td>{{ form.username.label_tag }}</td>
                    <td>{{ form.username }}</td>
                </tr>
                <tr>
                    <td>{{ form.email.label_tag }}</td>
                    <td>{{ form.email }}</td>
                </tr>
                <tr>
                    <td>{{ form.password.label_tag }}</td>
                    <td>{{ form.password }}</td>
                </tr>
                <tr>
                    <td>{{ form.password2.label_tag }}</td>
                    <td>{{ form.password2 }}</td>
                </tr>

            </table>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}